# Generated by Django 3.0 on 2020-04-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
